indexSuccess:
  javascripts:    [thickbox-compressed.js,channel.js]
  stylesheets:    [thickbox.css]
programsSuccess:
  stylesheets: [smoothness/jquery-ui-1.8.2.custom.css,thickbox.css,auto_complete.css]
  javascripts: [thickbox.js,auto_complete.js,jquery-ui-1.8.2.custom.min.js, -jquery-ui-i18n.min.js,DateTimeMask.js,DateTimeMask.js,-jquery.uitableedit.js]
