prod:
  photo:
    type: MogilefsStorage
    config: {hosts: "172.30.95.159:7001", domain: "5itv", class: "image"}

  static_url: http://epgimg.henancatv.com/
  #static_url: http://image.epg.huan.tv/

  huan_uc_url: http://61.145.165.154:8080/uc/json
  #lct_server_url: http://118.194.161.67:8080/lct-server/
  lct_server_url: http://192.168.10.71:8080/lct-server/

  memcache:
    servers:
      config_one: {host: "172.30.95.160", port: 11211}
    compression : 0
    lefttime : 7200

  php_path: /hwdata/php/bin/
  project_path:  /hwdata/www/hnepg/

dev:
  photo:
    type: MogilefsStorage
    config: {hosts: "172.30.95.159:7001", domain: "5itv", class: "image"}
  
  static_url: http://epgimg.henancatv.com/
  #static_url: http://image.epg.huan.tv/

  huan_uc_url: http://61.145.165.154:8080/uc/json
  #lct_server_url: http://118.194.161.67:8080/lct-server/
  lct_server_url: http://192.168.10.71:8080/lct-server/

  memcache:
    servers:
      config_one: {host: "172.30.95.160", port: 11211}
    compression : 0

  php_path: /hwdata/php/bin/
  project_path:  /hwdata/www/hnepg/

