ev:
  master:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=172.30.95.155;port=3306;dbname=epg'
      username: epg
      password: epgpass
  mondongo:
    class: sfMondongoDatabase
    param:
      server: mongodb://epg:epgpass@172.30.95.157:27017
      database: epg
prod:
  master:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=172.30.95.155;port=3306;dbname=epg'
      username: epg
      password: epgpass
  mondongo:
    class: sfMondongoDatabase
    param:
      server: mongodb://epg:epgpass@172.30.95.157:27017
      database: epg
