indexSuccess:
  javascripts:    [thickbox-compressed.js,channel.js]
  stylesheets:    [thickbox.css]

editSuccess:
  javascripts: [jquery.fancybox-1.3.4.pack.js]
  stylesheets: [fancybox-1.3.4.css]

importSuccess:
   stylesheets:   [smoothness/jquery-ui-1.8.2.custom.css,thickbox.css,auto_complete.css]
   javascripts: [thickbox.js,auto_complete.js,jquery-ui-1.8.2.custom.min.js, -jquery-ui-i18n.min.js,DateTimeMask.js,DateTimeMask.js,-jquery.uitableedit.js]

tempSuccess:
   stylesheets:   [smoothness/jquery-ui-1.8.2.custom.css,thickbox.css,auto_complete.css]
   javascripts: [thickbox.js,auto_complete.js,jquery-ui-1.8.2.custom.min.js, -jquery-ui-i18n.min.js,DateTimeMask.js,DateTimeMask.js,-jquery.uitableedit.js]

deletedSuccess:
   stylesheets:   [smoothness/jquery-ui-1.8.2.custom.css,thickbox.css,auto_complete.css]
   javascripts: [thickbox.js,auto_complete.js,jquery-ui-1.8.2.custom.min.js, -jquery-ui-i18n.min.js,DateTimeMask.js,DateTimeMask.js,-jquery.uitableedit.js]

has_layout:     true
layout:         layout  