indexSuccess:
   stylesheets:   [smoothness/jquery-ui-1.8.2.custom.css,thickbox.css,auto_complete.css]
   javascripts:   [jquery-ui-1.8.2.custom.min.js, jquery-ui-i18n.min.js,auto_complete.js, -program.js,thickbox-compressed,DateTimeMask.js,program_program.js]
