# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        EPG 节目单
    #description:  symfony project
    #keywords:     symfony, project
    #language:    zh-CN
    #robots:       index, follow

  stylesheets:    [base.css]

  javascripts:    [jquery-1.4.3.min.js, jquery.ui.widget.js, jquery.tvui.js, nav.js]

  has_layout:     false
  layout:         layout
