indexSuccess:
  javascripts:    [thickbox-compressed.js,channel.js]
  stylesheets:    [thickbox.css]

editSuccess:
  javascripts: [jquery.mousewheel-3.0.4.pack.js,jquery.fancybox-1.3.4.pack.js,thickbox.js,auto_complete.js,jquery-ui-1.8.2.custom.min.js]
  stylesheets: [fancybox-1.3.4.css,smoothness/jquery-ui-1.8.2.custom.css]

addSuccess:
  javascripts: [jquery.mousewheel-3.0.4.pack.js,jquery.fancybox-1.3.4.pack.js,thickbox.js,auto_complete.js,jquery-ui-1.8.2.custom.min.js]
  stylesheets: [fancybox-1.3.4.css,smoothness/jquery-ui-1.8.2.custom.css]

listwikisSuccess:
  javascripts: [jquery.mousewheel-3.0.4.pack.js,jquery.fancybox-1.3.4.pack.js,thickbox.js,auto_complete.js,jquery-ui-1.8.2.custom.min.js]
  stylesheets: [fancybox-1.3.4.css,smoothness/jquery-ui-1.8.2.custom.css]
  
addwikiSuccess:
  javascripts: [jquery.mousewheel-3.0.4.pack.js,jquery.fancybox-1.3.4.pack.js,thickbox.js,auto_complete.js,jquery-ui-1.8.2.custom.min.js]
  stylesheets: [fancybox-1.3.4.css,smoothness/jquery-ui-1.8.2.custom.css,auto_complete.css]
  
editwikiSuccess:
  javascripts: [jquery.mousewheel-3.0.4.pack.js,jquery.fancybox-1.3.4.pack.js,thickbox.js,auto_complete.js,jquery-ui-1.8.2.custom.min.js]
  stylesheets: [fancybox-1.3.4.css,smoothness/jquery-ui-1.8.2.custom.css,auto_complete.css]
  
loadWikiSuccess:
  has_layout:     false