# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

new:
  credentials: program_index_new

create:
  credentials: program_index_new

delete:
  credentials: program_index_del

index:
  credentials: program_index_show

edit:
  credentials: program_index_edit

update:
  credentials: program_index_edit

batchDelete:
  credentials: program_index_del
