# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        EPG 节目单
    #description:  symfony project
    #keywords:     symfony, project
    language:    zh-CN
    #robots:       index, follow

  stylesheets:    [base.css, merge.css]

  javascripts:    [jquery-1.4.2.min.js, epg2_6.js]

  has_layout:     true
  layout:         layout
