indexSuccess:
  javascripts:    [thickbox-compressed.js,channel.js,jquery-1.8.2.js,jquery-ui.js]
  stylesheets:    [thickbox.css,jquery-ui.css]
editSuccess:
  javascripts: [jquery.fancybox-1.3.4.pack.js]
  stylesheets: [fancybox-1.3.4.css]