# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

new:
  credentials: wiki_new

create:
  credentials: wiki_new

delete:
  credentials: wiki_del

index:
  credentials: wiki_show

edit:
  credentials: wiki_edit

update:
  credentials: wiki_edit

batchDelete:
  credentials: wiki_del
