dev:
  master:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=192.168.10.70;port=3306;dbname=epg_hn'
      username: epg_hn
      password: epgpass
  mondongo:
    class: sfMondongoDatabase
    param:
      server: mongodb://epg:epgpass@192.168.10.71:27017
      database: epg_hn
prod:
  master:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=192.168.10.70;port=3306;dbname=epg_hn'
      username: epg_hn
      password: epgpass
  mondongo:
    class: sfMondongoDatabase
    param:
      server: mongodb://epg:epgpass@192.168.10.71:27017
      database: epg_hn
